### ISSUE TITLE
cannot find -lopenal-soft-1_d

### ISSUE THREAD

**Issue by bruno-m-antunes-alb** [madmaw/marmalade-openal#7]
Just download your project, and double-clicked the freealut-hello_world.mkb.

When trying to run it (using Xcode 5.0.2, and Marmalade 7.0.2) i got this error:

ld: cannot find -lopenal-soft-1_d
collect2: ld returned 1 exit status
Command /Users/MY_USERNAME/.config/marmalade/root/s3e/bin/wrappers/arm-none-eabi-gcc failed with exit code 1

**Comment by madmaw** [comment]
Hi, it looks like one of the compiled binaries for openal-soft-1.13 isn't being found (linker errors are always fun), might be worth having a search around in the build directories and see if the "openal-soft-1_d" file is there, or it's something slightly different, or missing entirely. Unfortunately it's been a while since I had a valid license for Marmalade, so I can't help you much with this, but perhaps one of the other contributers will be able to look into this. I had a quick look at the MKB files and they seem fine. I guess my only other starting point would be that I did most of the initial port in Windows, I'm not sure what the other guys use.

While some people have done some great work on this, it's still a pretty raw port in terms of user-friendliness. If you do manage to solve the problem, I'd happily accept a patch if you wanted to commit it.
