### ISSUE TITLE
cracking on PC

### ISSUE THREAD

**Issue by frankinshtein** [madmaw/marmalade-openal#8]
Hi!
You did good work but it is not usable until cracking on PC would be fixed.
Any chances that it would be fixed soon?

**Comment by madmaw** [comment]
Probably not unless you have a go at fixing it yourself.

Depending on your requirements (e.g., whether you need actual 3D/stereo sound) you could try writing a separate driver that uses a lowest-common-denominator approach (e.g. mono sound) and enable that in the windows build of your app. My Marmalade licence is long expired, but I seem to recall that most of my testing was on PC and, while the implementation I wrote was far inferior to the latest one, it didn't crackle (maybe? it was a while go), so that could be a good starting point. Have a look through the commit history.

If you do write a separate driver, or patch the existing one, please consider checking any changes back in.

**Comment by vedran-** [comment]
Hey,
I have new version of openal implementation, I have been working on it for a past few months. There have been many problems, but I think I have them all solved now - it does not crack any more and it uses much less CPU than current implementation (and still manages to properly synchronize all threads). My game is already released with it, and there haven't been any problems.
I will upload new version in the next few hours.

**Comment by vedran-** [comment]
@madmaw I created pull request with new version. I wanted to ask you, could you possibly give me admin rights on this project? It seems I always have to return to it :)

**Comment by madmaw** [comment]
Done, you're now a collaborator, which I think means you can commit directly. Let me know if there are any problems.

**Comment by madmaw** [comment]
Oh, and great work as always!

**Comment by vedran-** [comment]
@madmaw Thanks!

**Comment by frankinshtein** [comment]
thank you! it is ok now
